# Generated by Django 4.2 on 2023-09-01 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chattapp', '0002_friend_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChattMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='chattapp.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chattapp.profile')),
            ],
            options={
                'verbose_name': 'ChattMessage',
                'verbose_name_plural': 'ChattMessages',
            },
        ),
    ]
